# Generated by Django 5.1.7 on 2025-04-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
